name: 'Verify Pull Request Labels'
author: 'Jesus Vasquez'
description: 'Verify that the PR has a valid label'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  required-type-labels:
    description: 'label for type of PR. for instance bugfix'
    required: true
  required-component-labels:
    description: 'label for which component a PR is related. for instance OP'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --github_token=${{ inputs.github-token }}
    - --required_labels=${{ inputs.required-type-labels }}
    - --required_labels=${{ inputs.required-component-labels }}
