on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_pr_labels:
    runs-on: ubuntu-latest
    name: Verify that the PR has labels
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check PR labels
        uses: ./
        id: verify-pr-label
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          required-type-labels: 'bug, enhancement, purge, feature'
          required-component-labels: 'op, system, eager, build, xla, python, ci, test, tooling'
